repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-toml
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: c4654a7e007c9619a5eb63c39a456572a0fa1851  # frozen: 0.38.0
  hooks:
    - id: check-dependabot
    - id: check-github-workflows
      args: ["--verbose"]

- repo: https://github.com/asottile/reorder-python-imports
  rev: 5e38415c12154247a099c7023c210e3d458275b5  # frozen: v3.17.0
  hooks:
  -   id: reorder-python-imports

- repo: https://github.com/psf/black
  rev: 87928e6d6761a4a6d22250e1fee5601b3998086e  # frozen: 26.5.1
  hooks:
  -   id: black

- repo: https://github.com/brokenpip3/pre-commit-hooks
  rev: dd7b3821637ba3c3a8628ad487fd84edec8006f2  # frozen: 0.0.1
  hooks:
    - id: github-actions-hash
      files: ^.github/workflows/.*\.(yml|yaml)$ # limit only to github workflows

- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    types: [python]
    files: ^jcli/
    entry: pytest -v -s .
    language: system
    pass_filenames: false
