repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-toml
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 84080c769d17e250eb32ac0d10662c7bf03ad346  # frozen: 0.31.3
  hooks:
    - id: check-dependabot
    - id: check-github-workflows
      args: ["--verbose"]

- repo: https://github.com/asottile/reorder-python-imports
  rev: fd0b4e1292716bcd12a396b86af1d1271aaaa62c  # frozen: v3.14.0
  hooks:
  -   id: reorder-python-imports

- repo: https://github.com/psf/black
  rev: 8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b  # frozen: 25.1.0
  hooks:
  -   id: black

- repo: https://github.com/brokenpip3/pre-commit-hooks
  rev: dd7b3821637ba3c3a8628ad487fd84edec8006f2  # frozen: 0.0.1
  hooks:
    - id: github-actions-hash
      files: ^.github/workflows/.*\.(yml|yaml)$ # limit only to github workflows

- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    types: [python]
    files: ^jcli/
    entry: pytest -v -s .
    language: system
    pass_filenames: false
