name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  pre-commit-update:
    name: PreCommitHooksUpdate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Update pre-commit hooks
        uses: brokenpip3/action-pre-commit-update@24b7a510db4356b7cb0a2d0b8f72d1226fa7195b # 0.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
