name: CI
on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
jobs:
  pre-commit:
    name: PreCommit
    runs-on: ubuntu-latest
    steps:
    - uses: NixOS/nix-installer-action@228d8a956062db04221c97c2794ea443194824aa
    - name: Check out code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: nix checks
      run: nix flake check
    - name: nix pre-commit
      run: nix develop . --command pre-commit run --show-diff-on-failure
