name: CI
on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
jobs:
  pre-commit:
    name: PreCommit
    runs-on: ubuntu-latest
    steps:
    - uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6
      with:
        extra-conf: |
          experimental-features = nix-command flakes
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: nix checks
      run: nix flake check
    - name: nix pre-commit
      run: nix develop . --command pre-commit run --show-diff-on-failure
